on:
  push:         { "branches": [ "main" ] }
  pull_request: { "branches": [ "main" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        otp: [20.3, 21.3, 22.3, 23.3, 24.0]
        elixir: [1.9.4, 1.10.4, 1.11.4, 1.12.2]
        exclude:
          - otp: 20.3
            elixir: 1.10.4
          - otp: 20.3
            elixir: 1.11.4
          - otp: 20.3
            elixir: 1.12.2
          - otp: 21.3
            elixir: 1.12.2
          - otp: 23.3
            elixir: 1.9.4
          - otp: 24.0
            elixir: 1.9.4
          - otp: 24.0
            elixir: 1.10.4
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Get Dependencies
        run: mix deps.get
      - name: Compile Dependencies
        run: mix deps.compile
      - name: Compile Project
        run: mix compile
      - name: Run Tests
        run: mix test
      - name: Run Credo
        run: mix credo --strict
